---
title: "loops-prep"
author: "Davinder Singh"
date: "2023-04-05"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Basic for loops in R
```{r}
#for(item in list_of_items){
  #do_something(item)
#}
```

```{r}
volumes <- c (1.6, 3, 8)
for (volume in volumes){
  mass <- 2.65 * volume^0.9
  mass_lb <- mass *2.2
  print(mass)
  print(mass_lb )
}
```

# looping by index
```{r}
volumes <- c (1.6, 3, 8)
masses <- vector(length = length(volumes), mode = "numeric")
for(i in 1:length(volumes)){
  mass <- 2.65 * volumes[i]^0.9
  masses[i] <- mass
}
```

#loop over multiple objects
```{r}
volumes <- c (1.6, 3, 8)
b0 <- c(2.65, 1.28, 3.29)
b1 <- c(0.9, 1.1, 1.2)
masses <- vector(length = length(volumes), mode = "numeric")
for(i in 1:length(volumes)){
  mass <- b0[i] * volumes[i]^b1[i]
  masses[i] <- mass
}
```

# looping using functions
```{r}
estmass <- function(volume){
  if (volume > 5){
    mass <- 2.65 * volume ^0.9
  } else {
    mass <- NA
  }
  return(mass)
}
volumes <- c (1.6, 3, 8)
masses <- vector(mode = "numeric", length = length(volumes))
for (i in 1:length(volumes)){
  mass <- estmass(volumes[i])
}
masses_apply <- sapply(volumes, estmass)
```

# looping over files
```{r}
#download.file("https://www.datacarpentry.org/semester-niology/data/locations.zip", "locations.zip")
#unzip("locations.zip")
#data_files <- list.files(pattern = "locations-")
#results <- vector(mode = "intenger", length = length(data_files))
# for (i in 1:length(data_files)){
#data <- read.csv(data_files[i])
#count <- nrow(data)
#restults[i] <- count
#}
```

